# Generated by Django 3.1.2 on 2021-03-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
